dev_mysql:
  image: mysql:latest
  container_name: spring-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456789
    - MYSQL_DATABASE=mydb
  ports:
    - 3306:3306
  volumes:
    - ./db-dump-dev:/docker-entrypoint-initdb.d
  restart: always
